# Generated by Django 2.2.3 on 2019-07-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='fiscal_doc_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fiscal_drive_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fiscal_sign',
            field=models.IntegerField(),
        ),
    ]
