# Generated by Django 2.2.3 on 2019-07-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_auto_20190718_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='fiscal_drive_num',
            field=models.IntegerField(unique=True),
        ),
    ]
