# Generated by Django 2.2.3 on 2019-07-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20190718_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='fiscal_doc_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fiscal_sign',
            field=models.IntegerField(unique=True),
        ),
    ]
